In [1]:
import pandas as pd    
import numpy as np   
import matplotlib.pyplot as plt 
from matplotlib.ticker import FuncFormatter, MultipleLocator, AutoMinorLocator

In [2]:
df = pd.read_excel(r'E:\all_draw\CTD\营养盐数据.xlsx')
df['站位'] = df['站位'].fillna(method='ffill')
df

,站位,深度(m),经度(E),纬度(N),磷酸盐,硝酸盐,亚硝酸盐,铵盐,硅酸盐
0,NaN,NaN,NaN,NaN,μmol/L,μmol/L,μmol/L,μmol/L,μmol/L
1,QB03,5.0,142.076788,0.002646,0.177419,0.285714,0.142857,0.428571,2.921429
2,QB03,25.0,142.076788,0.002646,0.16129,0.214286,0.142857,0.428571,1.553571
3,QB03,50.0,142.076788,0.002646,0.177419,0.285714,0.142857,0.5,1.128571
4,QB03,75.0,142.076788,0.002646,0.209677,0.428571,0.285714,0.5,1.564286
...,...,...,...,...,...,...,...,...,...
556,QB17,1000.0,135.092234,17.931348,2.677419,39.571429,0.285714,4.214286,58.542857
557,QB17,1500.0,135.092234,17.931348,2.903226,38.142857,0.285714,4.5,76.375
558,QB17,2000.0,135.092234,17.931348,2.629032,39,0.357143,5.071429,158.178571
559,QB17,3000.0,135.092234,17.931348,2.854839,36.857143,0.571429,8.5,158.628571
560,QB17,4000.0,135.092234,17.931348,2.403226,37.428571,0.357143,3.142857,159.628571

In [3]:
stations = []
for i in df['站位']:
    stations.append(i)
stations = list(set(stations))
print(stations)

['E163-10', 'QB16', 'QB15', 'QB17', 'E142-07', 'QB10', 'E163-08', 'E163-04', 'QB12', 'QB11', 'FB02', 'QB19', 'E163-11', 'QB-07new', 'QB05', 'E142-10', 'E163-09', 'QB09', 'N3-05', 'QB06', 'FB01', 'QB01', 'N3-03', 'QB02', 'E163-03', 'Mk-03', 'E163-06', 'E163-01', 'E163-02', 'QB04', 'QB03', 'E142-06', nan, 'QB14', 'E142-5', 'QB08', 'QB07', 'EQ-03', 'E163-05', 'QB18', 'N3-01', 'E163-07']

In [26]:
plt.rcParams['font.sans-serif'] = ['SimHei']  # 用来正常显示中文标签
plt.rcParams['axes.unicode_minus'] = False  # 用来正常显示负号
plt.rcParams['font.size'] = 26

for station in stations:
    print(station)
    data = df[df['站位'] == station]
    depth = data['深度(m)'].values
    sio4 = data['硅酸盐'].values
    fig = plt.figure(figsize=(7, 12))
    ax = fig.add_subplot(111)
    ax.plot(sio4, depth, linewidth=5)
    ax.xaxis.set_major_locator(MultipleLocator(10))
    ax.xaxis.set_minor_locator(MultipleLocator(5))
    ax.yaxis.set_major_locator(MultipleLocator(1000))
    ax.yaxis.set_minor_locator(MultipleLocator(200))
    ax.tick_params(which='major', length=10, width=2, labelsize=20)
    ax.tick_params(which='minor', length=5, width=1, labelsize=20)
    # ax.grid(which='major', axis='both', linestyle='--')
    # ax.grid(which='minor', axis='both', linestyle=':')
    plt.ylabel('Depth (m)')
    plt.xlabel('SiO4-Si (μmol/L)')
    plt.yticks(rotation=60, fontsize=24)
    plt.xticks((0, 50, 100, 160), fontsize=24)
    plt.ylim(0,6000)
    plt.xlim(0, 160)
    
    # for i in range(len(depth)):
    #     ax.text(sio4[i], depth[i], float(sio4[i]), ha='center', va='baseline', fontsize=20)
            
    ax.spines[:].set_linewidth(2)
    ax.invert_yaxis()

    plt.savefig(f'2021cruice_{station}.png', dpi=300, bbox_inches='tight')
    plt.close()

E163-06
E163-01
E163-07
E163-03
QB18
E163-08
E163-02
E163-05
QB02
QB17
N3-05
E163-04
QB01
E163-10
QB12
QB10
QB06
QB15
E163-11
E142-07
E142-10
QB05
QB04
QB-07new
QB07
QB11
QB19
QB16
N3-03
FB02
EQ-03
FB01
nan
E163-09
QB03
E142-06
E142-5
QB14
N3-01
QB08
Mk-03
QB09

In [14]:
import os 
import re
lt = os.listdir()
for i in lt:
    ltre = re.match(r'2021cruice(.*)', i)
    if not ltre:
        os.remove(i)